In [46]:
from ucimlrepo import fetch_ucirepo 
  
iris = fetch_ucirepo(id=53) 
  
features = iris.data.features 
targets = iris.data.targets 

In [ ]:
import pandas as pd
import numpy as np

feature_names = ["sepal length", "sepal width", "petal length", "petal width"]

df = pd.DataFrame(features, columns=[f'{feature_names[i]}' for i in range(features.shape[1])])
df['target'] = targets

np.random.seed(42)

shuffled_indices = np.random.permutation(df.index)

train_indices = shuffled_indices[:int(len(shuffled_indices) * 0.8)]

train_data = df.loc[train_indices]

test_data = df.drop(train_indices)

print(f"Размер исходного набора данных: {len(df)}")
print(f"Размер обучающего множества: {len(train_data)}")
print(f"Размер тестового множества: {len(test_data)}")
train_data

In [ ]:
def df_metadata(df):
    num_rows = len(df)
        
    print(f"\nКоличество строк во множестве: {num_rows}")
        
    class_counts = df['target'].value_counts()
    print("\nКоличество объектов в каждом классе:")
    print(class_counts)
        
    missing_values_count = df.isna().sum()
    print("\nКоличество пропущенных значений:")
    print(missing_values_count)
        
    stats = df.describe()
    print("\nСтатистика для каждого параметра:")
    print(stats)

df_metadata(train_data)
#df_metadata(test_data)   

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def print_report(df, df_pred):
    accuracy = accuracy_score(df, df_pred)
    print(f"Точность модели на обучающем множестве: {accuracy:.5f}")

    report = classification_report(df, df_pred)
    print("\nОтчет о классификации:")
    print(report)

    conf_mat = confusion_matrix(df, df_pred)
    print("\nМатрица ошибок:")
    print(conf_mat)

def predict(x, y):
    gnb = GaussianNB()
    gnb.fit(x, y)
    return gnb.predict(x)

X_train = train_data.drop('target', axis=1)
y_train = train_data['target']

print_report(y_train, predict(X_train, y_train))

In [ ]:
X_train = train_data[['sepal length', 'sepal width']]
y_train = train_data['target']

print_report(y_train, predict(X_train, y_train))

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler

X_train = train_data[['sepal length', 'sepal width']]
y_train = train_data['target']

dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train, y_train)

print_report(y_train, dtc.predict(X_train))

Точность модели на обучающем множестве: 0.94167

Отчет о классификации:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        43
Iris-versicolor       0.85      1.00      0.92        39
 Iris-virginica       1.00      0.82      0.90        38

       accuracy                           0.94       120
      macro avg       0.95      0.94      0.94       120
   weighted avg       0.95      0.94      0.94       120


Матрица ошибок:
[[43  0  0]
 [ 0 39  0]
 [ 0  7 31]]
