In [5]:
from ucimlrepo import fetch_ucirepo 
  
iris = fetch_ucirepo(id=53) 
  
features = iris.data.features 
targets = iris.data.targets 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

feature_names = ["sepal length", "sepal width", "petal length", "petal width"]

df = pd.DataFrame(features, columns=[f'{feature_names[i]}' for i in range(features.shape[1])])
df['target'] = targets

X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

shuffled_indices = np.random.permutation(df.index)
train_indices = shuffled_indices[:int(len(shuffled_indices) * 0.8)]
train_data = df.loc[train_indices]
test_data = df.drop(train_indices)

print(f"Размер исходного набора данных: {len(df)}")
print(f"Размер обучающего множества: {len(X_train)}")
print(f"Размер тестового множества: {len(X_test)}")
X_train

In [31]:
def df_metadata(df):
    num_rows = len(df)
        
    print(f"\nКоличество строк во множестве: {num_rows}")
        
    class_counts = df['target'].value_counts()
    print("\nКоличество объектов в каждом классе:")
    print(class_counts)
        
    missing_values_count = df.isna().sum()
    print("\nКоличество пропущенных значений:")
    print(missing_values_count)
        
    stats = df.describe()
    print("\nСтатистика для каждого параметра:")
    print(stats)

#df_metadata(train_data)
#df_metadata(test_data)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def print_report(y_test, y_pred):
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Точность модели на обучающем множестве: {accuracy:.5f}")

    report = classification_report(y_test, y_pred)
    print("\nОтчет о классификации:")
    print(report)

    conf_mat = confusion_matrix(y_test, y_pred)
    print("\nМатрица ошибок:")
    print(conf_mat)

def predict(x, y, x_test):
    gnb = GaussianNB()
    gnb.fit(x, y)
    return gnb.predict(x_test)

print_report(y_test, predict(X_train, y_train, X_test))

In [70]:
def get_specific_features(selected_features):
    all_features = list(iris.data.features.columns)

    feature_indices = {name: i for i, name in enumerate(all_features)}

    X = iris.data.features.iloc[:, [feature_indices[feat] for feat in selected_features]]
    y = iris.data.targets
    return train_test_split(X, y, test_size=0.2, random_state=42)

In [71]:
X_train, X_test, y_train, y_test = get_specific_features(['sepal length', 'sepal width'])
print_report(y_test, predict(X_train, y_train, X_test))

Точность модели на обучающем множестве: 0.90000

Отчет о классификации:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.88      0.78      0.82         9
 Iris-virginica       0.83      0.91      0.87        11

       accuracy                           0.90        30
      macro avg       0.90      0.90      0.90        30
   weighted avg       0.90      0.90      0.90        30


Матрица ошибок:
[[10  0  0]
 [ 0  7  2]
 [ 0  1 10]]


d:\python_projects\ML\lab2\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

X_train, X_test, y_train, y_test = get_specific_features(['sepal length', 'sepal width'])

dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train, y_train)

print_report(y_test, dtc.predict(X_test))
plt.figure(figsize=(20,10))
plot_tree(dtc, filled=True, class_names=['setosa', 'versicolor', 'virginica'], feature_names=['sepal length', 'sepal width'])
plt.show()

In [ ]:
from sklearn import svm

X_train, X_test, y_train, y_test = get_specific_features(['sepal length', 'sepal width'])

svc = svm.SVC(kernel='rbf', gamma='scale')
svc.fit(X_train, y_train)

print_report(y_test, svc.predict(X_test))